name: CI/CD pipeline

on:
  workflow_dispatch:

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    env:
        TF_VAR_docker_username: ${{ secrets.DOCKER_USERNAME }}
        TF_VAR_docker_password: ${{ secrets.DOCKER_PASSWORD }}
        TF_VAR_image_name: ${{ secrets.DOCKER_USERNAME }}/node-hello:latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: |
          npm install --save-dev eslint @eslint/js
          npx eslint .
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/node-hello:latest .

      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/node-hello:latest

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8  # or whatever version you're using

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
